openapi: 3.0.3
info:
  version: 1.0.0
  title: Cart Microservice Product service API
  description: Manages product inventory
  contact:
    name: AdeThorMiwa
    email: BenDaMyth@gmail.com
x-service-id: product
x-organization: rust
tags:
  - name: product
paths:
  /products:
    get:
      security:
        - authToken: []
      tags:
        - product
      summary: Fetch product list
      operationId: getProductList
      x-visibility: public
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
  securitySchemes:
    authToken:
      type: apiKey
      name: x-auth-token
      in: header
x-source-repository: MiscellaneousMinds/rms
x-source-path: product-service/spec/api-spec.yaml
servers:
  - url: http://product.rust
    description: Service Url from within cluster
  - url: https://staging-ingress.miscminds.com/rust/product
    description: URL to access staging deployment.
