openapi: 3.0.3
info:
  version: 1.0.5
  title: Stashio API
  description: Stashio monolith backend
  contact:
    name: AdeThorMiwa
    email: BenDaMyth@gmail.com
x-service-id: stashio-api
x-organization: AdeThorMiwa
x-lib-path: crates
x-lib-package-name: api_client
tags:
  - name: product
paths:
  /products:
    get:
      security:
        - authToken: []
      tags:
        - product
      summary: Fetch product list
      operationId: getProductList
      x-visibility: public
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
  securitySchemes:
    authToken:
      type: apiKey
      name: x-auth-token
      in: header
x-source-repository: AdeThorMiwa/stashio
x-source-path: specs/api-spec.yaml
servers:
  - url: http://stashio-api.AdeThorMiwa
    description: Service Url from within cluster
  - url: https://staging-ingress.miscminds.com/AdeThorMiwa/stashio-api
    description: URL to access staging deployment.
