name: Validate and Generate
on:
  push:
    paths:
      - "services/**"
      - ".validaterc"
      - ".spectral.yml"
      - "generate.js"
      - "config.json"
      - "**/generate.yaml"

  workflow_dispatch:
    inputs: {}

env:
  GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}

jobs:
  validateSpecs:
    name: Validate OpenAPI Specs
    runs-on: ubuntu-latest
    outputs:
      build: ${{steps.confirm-build-clients.outputs.build}}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install NPM
        run: npm ci
      - name: Run Validation
        run: |
          ls services/**/*.y*ml | xargs ./node_modules/.bin/lint-openapi -e
      - id: confirm-build-clients
        name: Confirm Client Build
        run: |
          git fetch --all --tags
          api_version=$(node ./version-bump.js --version)
          echo "API version is: ${api_version}"
          (git tag | grep $api_version && echo "build=no" >> $GITHUB_OUTPUT) || (echo "build=yes" >>  $GITHUB_OUTPUT)

  generateClientSource:
    name: Generate Sources
    runs-on: ubuntu-latest
    needs: validateSpecs
    env:
      OPENAPI_GENERATOR_VERSION: "6.1.0"
      AWS_S3_RESOURCE_BUCKET: "resources.miscelleneous-minds.com"

    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && needs.validateSpecs.outputs.build == 'yes'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: NPM Install
        run: npm ci

      - uses: actions/cache@v3
        id: codegencache
        with:
          path: codegen
          key: ${{ runner.os }}-openapi-generator-${{ env.OPENAPI_GENERATOR_VERSION }}

      - name: Download OpenAPI Generator
        if: steps.codegencache.outputs.cache-hit != 'true'
        run: |
          mkdir -p codegen
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/$OPENAPI_GENERATOR_VERSION/openapi-generator-cli-$OPENAPI_GENERATOR_VERSION.jar -O codegen/openapi-generator-cli.jar

      - name: Make Script
        run: |
          node ./generate.js
